CREATE SCHEMA IF NOT EXISTS MASTER AUTHORIZATION user1;
CREATE SCHEMA IF NOT EXISTS TENANT_ACME AUTHORIZATION user1;
CREATE SCHEMA IF NOT EXISTS TENANT_ARGUS AUTHORIZATION user1;

CREATE TABLE IF NOT EXISTS TENANT_ACME.NOTE(
    ID BIGSERIAL PRIMARY KEY,
    TITLE VARCHAR(32) NOT NULL,
    CONTENT VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS TENANT_ARGUS.NOTE(
    ID BIGSERIAL PRIMARY KEY,
    TITLE VARCHAR(32) NOT NULL,
    CONTENT VARCHAR(64)
);