# Configuration for spring application
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 10MB
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 8

# Set max number of retry times for login
login-attempts:
  max-number-of-attempts: 5
  failed-attempt:
    block-time: 1
    time-unit: DAYS
  time-window:
    time: 10
    time-unit: MINUTES
  email-message: We detected suspicious login attempts. Your account is blocked for 1 day from now.


