# Use Placeholder for sensitive information

# SSL Encryption
server.tomcat.max.threads=200
server.ssl.key-store-type=${SSL_KEYSTORE_TYPE}
server.ssl.key-store=${SSL_KEYSTORE}
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD}
server.ssl.key-alias=${SSL_KEY_ALIAS}
server.ssl.enabled=true
server.ssl.protocol=TLS

# Crypto
keystore.file=${KEYSTORE_FILE}
keystore.password=${KEYSTORE_PASSWORD}
key.password=${KEY_PASSWORD}
password.alias=${KEYSTORE_ALIAS}

# Mail
spring.mail.default-encoding=utf-8
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.protocol=smtps
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

# ReCaptcha
google.recaptcha.key.site=${RECAPTCHA_KEY_SITE}
google.recaptcha.key.secret=${RECAPTCHA_KEY_SECRET}
google.recaptcha.key.threshold=${RECAPTCHA_KEY_THRESHOLD}
google.recaptcha.key.url-template=${RECAPTCHA_KEY_URL_TEMPLATE}
recaptcha.read-timeout=${RECAPTCHA_READ_TIMEOUT}
recaptcha.connection-timeout=${RECAPTCHA_CONN_TIMEOUT}