server.port = 8443

# SSL Encryption
server.ssl.key-store-type=${SSL_KEYSTORE_TYPE}
server.ssl.key-store=${SSL_KEYSTORE}
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD}
server.ssl.key-alias=${SSL_KEY_ALIAS}
server.ssl.enabled=true
server.ssl.protocol=TLS